=== Alkhymia/Dual-Strike/MCCF/java/mccf/configuration-def.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:strike-devices:configuration" xmlns:c="urn:strike-devices:configuration" elementFormDefault="qualified">
  <xs:element name="configuration" type="c:Configuration"/>

  <xs:complexType name="Configuration">
    <xs:sequence>
      <xs:group ref="c:Infos"/>
      <xs:sequence>
        <xs:element name="device" type="c:Field"/>
        <xs:element name="version" type="c:Field"/>
        <xs:element name="page" type="c:Page" maxOccurs="unbounded"/>
      </xs:sequence>      
    </xs:sequence>
    <xs:attribute name="def-lang-version" fixed="1" use="required" type="xs:int"/>
    <xs:attribute name="lang" type="xs:language" use="required"/>
    <xs:attribute name="prefix" type="xs:ID" use="required"/>
    <xs:attribute name="icon-path" type="c:RelativePath"/>
  </xs:complexType>
  
  <xs:simpleType name="Field">
    <xs:restriction base="xs:byte">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:group name="Infos">
    <xs:sequence>
      <xs:element name="title" maxOccurs="unbounded" type="c:Info"/>
      <xs:element name="help" minOccurs="0" maxOccurs="unbounded" type="c:PathInfo"/>
    </xs:sequence>
  </xs:group>
  
  <xs:complexType name="Info" >
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="lang" type="xs:language"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="PathInfo">
    <xs:complexContent>
      <xs:extension base="c:Info">
        <xs:attribute name="path" type="c:RelativePath"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="Page">
    <xs:sequence>
      <xs:group ref="c:Infos"/>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="choice" type="c:ChoiceSetting"/>
        <xs:element name="boolean" type="c:BooleanSetting"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ChoiceSetting">
    <xs:sequence>
      <xs:group ref="c:Infos"/>
      <xs:element name="image" type="c:DescriptionImage" minOccurs="0"/>
      <xs:element name="option" type="c:Option" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="default" type="xs:IDREF" use="required">
      <xs:annotation><xs:documentation>
        This attribute has to refer to a option of the containing choice.
      </xs:documentation></xs:annotation>
    </xs:attribute>
    <xs:attribute name="prefix" type="c:SettingID"/>
  </xs:complexType>

  <xs:complexType name="BooleanSetting">
    <xs:complexContent>
      <xs:extension base="c:Setting">
        <xs:sequence>
          <xs:element name="image" type="c:DescriptionImage" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="default" type="xs:boolean"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Option">
    <xs:complexContent>
      <xs:extension base="c:Setting">
        <xs:sequence>
          <xs:element name="requires" type="xs:IDREF" minOccurs="0" maxOccurs="unbounded">
            <xs:annotation><xs:documentation>
              An element of this kind imposes two constraints on the configuration:
                -The containing option can only be activated if the referred
                 setting is set, i.e. in case of a boolean it is enabled and
                 in case of an option it is the current selection of its
                 containing choice.
                -If the containing option is the current selection of its
                 containing choice, the referred setting is set fix, i.e.
                 in case of a boolean it is not disengageable and in case of an
                 option the other options of its containing choice are not
                 selectable.
                 
              To prevent cascading changes and clashing requirements, the
              following cases must not occur (which the application has to check):
                -A choice A contains an option which is being required by a
                 choice B (A may be equal to B) and an option of A requires a
                 setting.
                -In one choice for a pair of options A and B, A is required
                 by a choice C, B is required by a choice D and C and D are
                 different choices.
            </xs:documentation></xs:annotation>
          </xs:element>
        </xs:sequence>      
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Setting" >
    <xs:group ref="c:Infos"/>
    <xs:attribute name="id" type="c:SettingID" use="required"/>
  </xs:complexType>
    
  <xs:simpleType name="SettingID">
    <xs:restriction base="xs:ID">
      <xs:pattern value="(\p{Lu}|_|\d)+"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="DescriptionImage">
    <xs:group ref="c:Infos"/>
    <xs:attribute name="path" type="c:RelativePath"/>
  </xs:complexType>

  <xs:simpleType name="RelativePath">
    <xs:restriction base="xs:string">
      <xs:pattern value="\w(/|\w|\.|\d| |-|_)*"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Alkhymia/Dual-Strike/MCCF/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="configuration2html.xsl" type="text/xsl"?>
<configuration
  xmlns="urn:strike-devices:configuration"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:strike-devices:configuration java/mccf/configuration-def.xsd"
  def-lang-version="1"
  lang="en"
  prefix="CFG_"
  icon-path="configuration.png"
  xmlns:xi="http://www.w3.org/2001/XInclude">
  
  <title>Dual Strike Configuration</title>
  <title lang="de">Dual Strike Konfiguration</title>
  <help path="configuration-help.html"/>
  <help lang="de" path="configuration-help_de.html"/>
  
  <device>2</device>
  <version>1</version>
  
  <page>
    <title>Defaults</title>
    <title lang="de">Standards</title>
    <help>Configure the default settings of the Dual Strike.</help>
    <help lang="de">Konfiguration der Dual Strike Standardeinstellungen.</help>
    
    <choice prefix="DEF_WORK_MODE_" default="PS3">
      <title>Default Working Mode</title>
      <title lang="de">Standard Arbeitsmodus</title>
      <help>The working mode which is activated on plugging in, if no button to change the working mode is pressed.</help>
      <help lang="de">Der Arbeitsmodus der aktiviert wird, falls kein Button um den Arbeitsmodus zu ändern gedrückt wird.</help>
      
      <option id="PS3">
        <title>PS3/PC Controller</title>
        <help>The Dual Strike works as a PS3 and PC controller.</help>
        <help lang="de">Das Dual Strike arbeitet als PS3 und PC Controller.</help>
        <requires>PS3_ENABLED</requires>
        <requires>FOO</requires>
      </option>

      <option id="MAME">
        <title>MAME Keyboard</title>
        <title lang="de">MAME Tastatur</title>
        <help>The Dual Strike works as a MAME compatible keyboard.</help>
        <help lang="de">Das Dual Strike arbeitet als eine MAME kompatible Tastatur.</help>
        <requires>MAME_ENABLED</requires>
      </option>

      <option id="XBOX">
        <title>XBox Controller</title>
        <help>The Dual Strike works as a XBox1 controller.</help>
        <help lang="de">Das Dual Strike arbeitet als eine XBox1 Controller.</help>
        <requires>XBOX_ENABLED</requires>
      </option>
      
      <option id="PT">
        <title>Pass-Through (XBox360 or other)</title>
        <title lang="de">Durchschleifen (XBox360 oder andere)</title>
        <help>The pass-through data connections are routed to the USB data connections on the Dual Strike PCB.</help>
        <help lang="de">Die Durschleif-Datenanschlüsse werden auf die USB Datenanschlüsse des Dual Strike PCB geleitet.</help>
        <requires>PT_ENABLED</requires>
      </option>
    </choice>
    
    <boolean id="PS3_ENABLED" default="true">
        <title>PS3/PC Controller</title>
        <help>The Dual Strike works as a PS3 and PC controller.</help>
        <help lang="de">Das Dual Strike arbeitet als PS3 und PC Controller.</help>
    </boolean>

    <boolean id="MAME_ENABLED" default="true">
        <title>MAME Keyboard</title>
        <title lang="de">MAME Tastatur</title>
        <help>The Dual Strike works as a MAME compatible keyboard.</help>
        <help lang="de">Das Dual Strike arbeitet als eine MAME kompatible Tastatur.</help>
    </boolean>
    
    <boolean id="XBOX_ENABLED" default="true">
        <title>XBox Controller</title>
        <help>The Dual Strike works as a XBox1 controller.</help>
        <help lang="de">Das Dual Strike arbeitet als eine XBox1 Controller.</help>
    </boolean>
    
    <boolean id="PT_ENABLED" default="true">
        <title>Pass-Through (XBox360 or other)</title>
        <title lang="de">Durchschleifen (XBox360 oder andere)</title>
        <help>The pass-through data connections are routed to the USB data connections on the Dual Strike PCB.</help>
        <help lang="de">Die Durschleif-Datenanschlüsse werden auf die USB Datenanschlüsse des Dual Strike PCB geleitet.</help>
    </boolean>
    
    <choice default="FOO">
      <title>Blubber</title>
      <option id="FOO"><title>FOO</title></option>
      <option id="BAR"><title>BAR</title></option>
      <option id="FOO_BAR"><title>FOO BAR</title></option>
      <option id="BLUBB"><title>Blubb</title></option>
      <option id="BLOB"><title>Blob</title></option>
    </choice>
  </page>
</configuration>
