=== Alkhymia/Dual-Strike/Configuration/java/dualstrike/configuration/configuration-def.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:strike-devices:configuration" xmlns:c="urn:strike-devices:configuration" elementFormDefault="qualified">
  <xs:element name="configuration" type="c:Configuration"/>

  <xs:complexType name="Configuration">
    <xs:sequence>
      <xs:group ref="c:Infos"/>
      <xs:element name="image" type="c:DescriptionImage" minOccurs="0"/>
      <xs:sequence>
        <xs:element name="device" type="c:Field"/>
        <xs:element name="version" type="c:Field"/>
        <xs:element name="page" type="c:Page" maxOccurs="unbounded"/>
      </xs:sequence>      
    </xs:sequence>
    <xs:attribute name="def-lang-version" fixed="1" use="required" type="xs:int"/>
    <xs:attribute name="lang" type="xs:language" use="required"/>
    <xs:attribute name="prefix" type="xs:ID" use="required"/>
    <xs:attribute name="icon-path" type="c:RelativePath"/>
  </xs:complexType>
  
  <xs:simpleType name="Field">
    <xs:restriction base="xs:byte">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:group name="Infos">
    <xs:sequence>
      <xs:element name="title" maxOccurs="unbounded" type="c:Info"/>
      <xs:element name="help" minOccurs="0" maxOccurs="unbounded" type="c:Info"/>
    </xs:sequence>
  </xs:group>
  
  <xs:complexType name="Info" >
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="lang" type="xs:language"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="Page">
    <xs:sequence>
      <xs:group ref="c:Infos"/>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="choice" type="c:ChoiceSetting"/>
        <xs:element name="boolean" type="c:BooleanSetting"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ChoiceSetting">
    <xs:sequence>
      <xs:group ref="c:Infos"/>
      <xs:element name="image" type="c:DescriptionImage" minOccurs="0"/>
      <xs:element name="option" type="c:Option" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="default" type="xs:IDREF"/>
    <xs:attribute name="prefix" type="c:SettingID"/>
  </xs:complexType>

  <xs:complexType name="BooleanSetting">
    <xs:complexContent>
      <xs:extension base="c:Setting">
        <xs:sequence>
          <xs:element name="image" type="c:DescriptionImage" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="default" type="xs:boolean"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Option">
    <xs:complexContent>
      <xs:extension base="c:Setting"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Setting" >
    <xs:group ref="c:Infos"/>
    <xs:attribute name="id" type="c:SettingID"/>
  </xs:complexType>
  
  <xs:simpleType name="SettingID">
    <xs:restriction base="xs:ID">
      <xs:pattern value="(\p{Lu}|_|\d)+"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="DescriptionImage">
    <xs:group ref="c:Infos"/>
    <xs:attribute name="path" type="c:RelativePath"/>
  </xs:complexType>

  <xs:simpleType name="RelativePath">
    <xs:restriction base="xs:string">
      <xs:pattern value="\w(/|\w|\.|\d| |-|_)*"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Alkhymia/Dual-Strike/Firmware/Trunk/configuration_editor/configuration_atmega8.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="configuration2html.xsl" type="text/xsl"?>
<configuration
  xmlns="urn:strike-devices:configuration"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:strike-devices:configuration java/mccf/configuration-def.xsd"
  def-lang-version="1"
  lang="en"
  prefix="CFG_"
  icon-path="configuration.png"
  xmlns:xi="http://www.w3.org/2001/XInclude">
  
  <title>Dual Strike Configuration (ATmega8)</title>
  <title lang="de">Dual Strike Konfiguration (ATmega8)</title>
  <help path="configuration-help.html"/>
  <help lang="de" path="configuration-help_de.html"/>
  
  <device>1</device>
  <version>2</version>
  
  <page>
    <title>Defaults</title>
    <title lang="de">Standards</title>
    <help>Configure the default settings of the Dual Strike.</help>
    <help lang="de">Konfiguration der Dual Strike Standardeinstellungen.</help>
    
    <choice prefix="DEF_WORK_MODE_" default="PS3">
      <title>Default Working Mode</title>
      <title lang="de">Standard Arbeitsmodus</title>
      <help>The working mode which is activated on plugging in, if no button to change the working mode is pressed.</help>
      <help lang="de">Der Arbeitsmodus der aktiviert wird, falls kein Button um den Arbeitsmodus zu ändern gedrückt wird.</help>
      
      <option id="PS3">
        <title>PS3/PC Controller</title>
        <help>The Dual Strike works as a PS3 and PC controller.</help>
        <help lang="de">Das Dual Strike arbeitet als PS3 und PC Controller.</help>
        <requires>WORK_MODE_PS3_ENABLED</requires>
      </option>
      
      <option id="PT">
        <title>Pass-Through (XBox360 or other)</title>
        <title lang="de">Durchschleifen (XBox360 oder andere)</title>
        <help>The pass-through data connections are routed to the USB data connections on the Dual Strike PCB.</help>
        <help lang="de">Die Durschleif-Datenanschlüsse werden auf die USB Datenanschlüsse des Dual Strike PCB geleitet.</help>
        <requires>WORK_MODE_PT_ENABLED</requires>
      </option>
    </choice>
    
    <boolean id="WORK_MODE_PS3_ENABLED" default="true">
        <title>PS3/PC Controller</title>
        <help>The Dual Strike works as a PS3 and PC controller.</help>
        <help lang="de">Das Dual Strike arbeitet als PS3 und PC Controller.</help>
    </boolean>
    
    <boolean id="WORK_MODE_PT_ENABLED" default="true">
        <title>Pass-Through (XBox360 or other)</title>
        <title lang="de">Durchschleifen (XBox360 oder andere)</title>
        <help>The pass-through data connections are routed to the USB data connections on the Dual Strike PCB.</help>
        <help lang="de">Die Durschleif-Datenanschlüsse werden auf die USB Datenanschlüsse des Dual Strike PCB geleitet.</help>
    </boolean>
    
    <choice default="DIGITAL_PAD">
      <title>Default Joystick Mode</title>
      <title lang="de">Standard Joystick-Modus</title>
      <help>The joystick mode which is activated on plugging in, if no joystick direction to change the joystick mode is activated.</help>
      <help lang="de">Der Joystick-Modus der aktiviert wird, falls keine Joystick-Richtung um den Joystick-Modus zu ändern aktiviert wird.</help>
      
      <option id="DIGITAL_PAD">
        <title>Digital Pad</title>
        <title lang="de">Digitales Pad</title>
        <help>The joystick works as a digital pad.</help>
        <help lang="de">Der Joystick arbeitet als digitales Pad.</help>
      </option>
      
      <option id="LEFT_STICK">
        <title>Left Analog Stick</title>
        <title lang="de">Linker Analoger Stick</title>
        <help>The joystick works as a left analogue joystick.</help>
        <help lang="de">Der Joystick arbeitet als ein linker analoger Stick.</help>
      </option>
      
      <option id="RIGHT_STICK">
        <title>Right Analog Stick</title>
        <title lang="de">Rechter Analoger Stick</title>
        <help>The joystick works as a right analogue joystick.</help>
        <help lang="de">Der Joystick arbeitet als ein rechter analoger Stick.</help>
      </option>
    </choice>
  </page>
  
  <page>
    <title>Hardware</title>
    <help>Settings related to the hardware.</help>
    <help lang="de">Einstellungen im Zusammenhang mit der Hardware.</help>

    <boolean id="HOME_EMU" default="false">
      <title>Home Button Emulation</title>
      <help>Pressing the Select and Start buttons simultaneously is recognized as pressing the Home button.</help>
      <help lang="de">Gleichzeitiges Aktivieren der Select und Start Buttons wird als Drücken des Home Buttons gewertet.</help>
    </boolean>

    <choice default="NO_EXTRA_PINS">
      <title>S3/S4 Function</title>
      <title lang="de">S3/S4 Funktion</title>
      <help>The function of the S3 and S4 connections on the Dual Strike PCB.</help>
      <help lang="de">Die Funktion der S3 und S4-Anschlüsse auf dem Dual Strike PCB.</help>
        
      <option id="NO_EXTRA_PINS">
        <title>Nothing</title>
        <title lang="de">Nichts</title>
        <help>S3 and S4 will not be used.</help>
        <help lang="de">S3 und S4 werden nicht verwendet.</help>
      </option>
      
      <option id="JOYSTICK_SWITCH_READ">
        <title>Joystick Switch Reading</title>
        <title lang="de">Joystick-Schalter Auslesen</title>
        <help>S3 and S4 should be connected to a SPCO switch as well as VCC to the center position pin.&lt;br/>
This applies to the PS3/PC working mode.&lt;br/>
If the switch is in the center position the digital pad will be activated. In the&lt;br/>
left position the left analogue stick will be activated. In the other position&lt;br/>
the right analogue stick will be activated.</help>
        <help lang="de">S3 und S4 sollten mit einem SPCO Schalter verbunden sein&lt;br/>
genauso wie VCC zum Anschluß der mittleren Position. Dies gilt für den PS3/PC Arbeitsmodus.&lt;br/>
Ist der Schalter in der mittleren Position wird das digitale Pad aktiviert. In der linken Position&lt;br/>
wird der linke analoge Stick aktiviert. In der rechten Position wird der rechte&lt;br/>
analoge Stick aktiviert.</help>
      </option>
      
      <option id="JOYSTICK_SWITCH_EMU">
        <title>Joystick Switch Emulation</title>
        <title lang="de">Joystick-Schalter Emulation</title>
        <help>S3 and S4 should be connected to the pins for a active-high SPCO 
switch of the pass-through PCB. This applies to the pass-through working mode.&lt;br/>
The joystick setting of the Dual Strike will set the pass-through PCB's switch -&lt;br/>
either by default setting or by activating an appropiate joystick direction while plugging in.</help>
        <help lang="de">S3 und S4 sollten mit den Anschlüssen für einen Active-High&lt;br/>
SPCO Schalter des durgeschliffenen PCBs verbunden sein.&lt;br/>
Dies gilt für den Durschleif-Arbeitsmodus.&lt;br/>
Die Joystick-Einstellung des Dual Strike wird den Schalter des durgeschliffenen&lt;br/> 
PCBs schalten - entweder durch Standard-Einstellung oder durch Aktivieren einer&lt;br/> 
entsprechenden Joystick-Richtung beim Einstecken.</help>
      </option>
      
      <option id="INVERTED_TRIGGERS">
        <title>Inverted Triggers</title>
        <title lang="de">Invertierte Trigger</title>
<help>S3 and S4 should be connected to the pins of active-low trigger buttons of&lt;br/>
the pass-through PCB while these are not connected to the MK and 4K buttons.&lt;br/>
This applies to the pass-through working mode.&lt;br/>
This will make the appropiate buttons work with active-high trigger PCBs.</help>
<help lang="de">S3 und S4 sollten mit den Anschlüssen für Active-Low Trigger des&lt;br/>
durgeschliffenen PCBs verbunden werden, solange diese nicht mit den MK und 4K&lt;br/>
Buttons verbunden sind.&lt;br/>
Dies gilt für den Durschleif-Arbeitsmodus.&lt;br/>
Damit funkionieren die entsprechenden Buttons mit Active-High Trigger PCBs.</help>
      </option>
    </choice>
  </page>
</configuration>

=== Alkhymia/Dual-Strike/Configuration/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration
  xmlns="urn:strike-devices:configuration"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:strike-devices:configuration java/dualstrike/configuration/configuration-def.xsd"
  def-lang-version="1"
  lang="en"
  prefix="CFG_">
  
  <title>Dual Strike Configuration</title>
  <title lang="de">Dual Strike Konfiguration</title>
  <help>The configuration of the Dual Strike PCB.</help>
  <help lang="de">Die Konfiguration des Dual Strike PCBs.</help>
  
  <device>1</device>
  <version>1</version>
  
  <page>
    <title>Defaults</title>
    <title lang="de">Standards</title>
    <help>Defaults for settings of the Dual Strike.</help>
    <help lang="de">Standards für Einstellungen des Dual Strike.</help>
    
    <choice prefix="DEF_WORK_MODE_" default="PS3">
      <title>Default Working Mode</title>
      <title lang="de">Standard Arbeitsmodus</title>
      
      <help>The working mode which is activated on plugging in if no button to change the working mode is pressed.</help>
      <help lang="de">Der Arbeitsmodus welcher aktiviert wird, falls kein Button um den Arbeitsmodus zu ändern gedrückt wird.</help>
      
      <option id="PS3">
        <title>PS3/PC Controller</title>
        <title lang="de">PS3/PC Controller</title>
        <help>The Dual Strike works as a PS3 and PC controller.</help>
        <help lang="de">Das Dual Strike arbeitet als PS3 und PC Controller.</help>
      </option>
      
      <option id="PT">
        <title>Pass-Through</title>
        <title lang="de">Durchschleifen</title>
        <help>The pass-through data connections are routed to the USB data connections on the Dual Strike PCB.</help>
        <help lang="de">Die Durschleif-Datenanschlüsse werden auf die USB Datenanschlüsse auf dem Dual Stiker PCB geleitet.</help>
      </option>

      <!-- 
      <option id="MAME">
        <title>MAME</title>
      </option>
      <option id="XBOX">
        <title>XBox</title>
      </option>
      <option id="WII">
        <title>Wii</title>
      </option>
       -->
    </choice>
    
    <choice default="DIGITAL_PAD">
      <title>Default Joystick Mode</title>
      <title lang="de">Standard Joystick-Modus</title>
      <help>The joystick mode which is activated on plugging in if no joystick direction to change the joystick mode is activated.</help>
      <help lang="de">Der Joystick-Modus welcher aktiviert wird, falls keine Joystick-Richtung um den Joystick-Modus zu ändern aktiviert wird.</help>
      
      <option id="DIGITAL_PAD">
        <title>Digital Pad</title>
        <title lang="de">Digitales Pad</title>
        <help>The joystick works as a digital pad.</help>
        <help lang="de">Der Joystick arbeitet als digitales Pad.</help>
      </option>
      
      <option id="LEFT_STICK">
        <title>Left Analog Stick</title>
        <title lang="de">Linker Analoger Stick</title>
        <help>The joystick works as a left analogue joystick.</help>
        <help lang="de">Der Joystick arbeitet als ein linker analoger Stick.</help>
      </option>
      
      <option id="RIGHT_STICK">
        <title>Right Analog Stick</title>
        <title lang="de">Rechter Analoger Stick</title>
        <help>The joystick works as a right analogue joystick.</help>
        <help lang="de">Der Joystick arbeitet als ein rechter analoger Stick.</help>
      </option>
    </choice>
  </page>
  
  <page>
    <title>Hardware</title>
    <help>Settings related to the hardware.</help>
    <help lang="de">Einstellungen im Zusammenhang mit der Hardware.</help>

    <boolean id="HOME_EMU" default="false">
      <title>Home Button Emulation</title>
      <help>Pressing the Select and Start buttons simultaneously is recognized as as pressing the Home button.</help>
      <help lang="de">Gleichzeitiges Aktivieren der Select und Start Buttons wird als Drücken des Home Buttons gewertet.</help>
    </boolean>

    <choice default="NO_EXTRA_PINS">
      <title>S3/S4 Function</title>
      <title lang="de">S3/S4 Funktion</title>
      <help>The function of the S3 and S4 connections on the Dual Strike PCB.</help>
      <help lang="de">Die Funktion der S3 und S4-Anschlüsse auf dem Dual Strike PCB.</help>
        
      <option id="NO_EXTRA_PINS">
        <title>Nothing</title>
        <title lang="de">Nichts</title>
        <help>S3 and S4 will not be used.</help>
        <help lang="de">S3 und S4 werden nicht verwendet.</help>
      </option>
      
      <option id="JOYSTICK_SWITCH_READ">
        <title>Joystick Switch Reading</title>
        <title lang="de">Joystick-Schalter Auslesen</title>
        <help>S3 and S4 should be connected to a SPCO switch as well as VCC to the center position pin. This applies to the PS3/PC working mode.
In the center position the digital pad will be activated. In the left position the left analogue stick will be activated. If the other position the right analogue stick will be activated.</help>
        <help lang="de">S3 und S4 sollten mit einem SPCO Schalter verbunden sein genauso wie VCC zum Anschluß der mittleren Position. Dies gilt für den PS3/PC Arbeitsmodus.
In der mittleren Position wird das digitale Pad aktiviert. In der linken Position wird der linke analoge Stick aktiviert. In der rechten Position wird der rechte analoge Stick aktiviert.</help>
      </option>
      
      <option id="JOYSTICK_SWITCH_EMU">
        <title>Joystick Switch Emulation</title>
        <title lang="de">Joystick-Schalter Emulation</title>
        <help>S3 and S4 should be connected to the pins for a active-high SPCO switch of the pass-through PCB. This applies to the pass-through working mode.
The joystick setting of the Dual Strike will set the pass-through PCB's switch - either by default setting or by activating an appropiate joystick direction while plugging in.</help>
        <help lang="de">S3 und S4 sollten mit den Anschlüssen für einen Active-High SPCO Schalter des durgeschliffenen PCBs verbunden sein. Dies gilt für den Durschleif-Arbeitsmodus.
Die Joystick-Einstellung des Dual Strike wird den Schalter des durgeschliffenen PCBs schalten - entweder durch standard Einstellung oder durch aktivieren einer entsprechenden Joystick-Richtung beim Einstecken.</help>
      </option>
      
      <option id="INVERTED_TRIGGERS">
        <title>Inverted Triggers</title>
        <title lang="de">Invertierte Trigger</title>
        <help>S3 and S4 should be connected to the pins of active-low trigger buttons of the pass-through PCB while these are not connected to the MK and 4K buttons. This applies to the pass-through working mode.
This will make the appropiate buttons work with active-high trigger PCBs.</help>
        <help lang="de">S3 und S4 sollten mit den Anschlüssen für Active-Low Trigger des durgeschliffenen PCBs verbunden werden, solange diese nicht mit den MK und 4K Buttons verbunden sind. Dies gilt für den Durschleif-Arbeitsmodus.
Damit funkionieren die entsprechenden Buttons mit Active-High Trigger PCBs.</help>
      </option>
      
      <!-- 
      <option id="FOO">
        <title>Foo</title>
      </option>
       -->
    </choice>
  </page>
</configuration>
